require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LinksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Link. As you add validations to Link, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {FactoryGirl.attributes_for(:link)}

  let(:invalid_attributes) { {long_url: nil} }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LinksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all links as @links" do
      link = Link.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:links)).to eq([link])
    end

    it "assigns new link to @link" do
      get :index, {}, valid_session
      expect(assigns(:link)).to be_a_new(Link)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Link" do
        expect {
          post :create, {:link => valid_attributes}, valid_session
        }.to change(Link, :count).by(1)
      end

      it "assigns a newly created link as @link" do
        post :create, {:link => valid_attributes}, valid_session
        expect(assigns(:link)).to be_a(Link)
        expect(assigns(:link)).to be_persisted
      end

      it "redirects to link list" do
        post :create, {:link => valid_attributes}, valid_session
        expect(response).to redirect_to(links_url)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved link as @link" do
        post :create, {:link => invalid_attributes}, valid_session
        expect(assigns(:link)).to be_a_new(Link)
      end

      it "re-renders the 'index' template" do
        link = Link.create! valid_attributes
        post :create, {:link => invalid_attributes}, valid_session
        expect(assigns(:links)).to eq([link])
        expect(response).to render_template("index")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested link" do
      link = Link.create! valid_attributes
      expect {
        delete :destroy, {:id => link.to_param}, valid_session
      }.to change(Link, :count).by(-1)
    end

    it "redirects to the links list" do
      link = Link.create! valid_attributes
      delete :destroy, {:id => link.to_param}, valid_session
      expect(response).to redirect_to(links_url)
    end
  end

  describe "GET #redirect" do
    it "redirect the requested code for @link.long_url" do
      link = Link.create! valid_attributes
      get :redirect, {:code => link.code}, valid_session
      expect(response).to redirect_to(link.long_url)
    end

    it "redirect to not found page when code doesn't exist" do
      link = Link.create! valid_attributes
      get :redirect, {:code => "#{link.code}123"}, valid_session
      expect(response).to redirect_to(links_url)
      expect(flash.now[:alert]).to eq("Erro: Link não existe!")
    end
  end

end
